### ISSUE TITLE
Compression of README GIFs

### ISSUE THREAD

**Issue by gezeta-id** [brenocq/implot3d#6]
Hi.

Some people were complaining about the images in the README taking a while to load or not even loading at all sometimes.

As a suggestion, you may want to consider compressing the GIFs.

In case you're interested, I've done a quick and dirty test and it brings the size from ~23MB to ~10MB which is a nice improvement without bringing down the quality _too much_.

If you want them, here are the compressed images:

![1](https://github.com/user-attachments/assets/aeb98588-4aa6-41a5-9742-706071f96356)
![2](https://github.com/user-attachments/assets/1b3e50cd-c703-4e5b-805f-7ff8b508369a)
![3](https://github.com/user-attachments/assets/309f5f03-e29a-4261-9e0e-1d28fb2d8fe8)
![4](https://github.com/user-attachments/assets/451d47c8-2025-40d4-bcaa-d68e4d657e70)
![5](https://github.com/user-attachments/assets/ad8732c5-1380-4a93-bb02-df89b427e284)
![6](https://github.com/user-attachments/assets/d743e34a-954f-4dcb-b347-10424cea4871)

**Comment by gezeta-id** [comment]
My pleasure. It's the least I could do )

**Comment by brenocq** [comment]
Hi @gezeta-id!

I was checking your GIFs and I noticed that we can compress it even further. Because I still have the original videos, I converted them again to `.gif`, but this time I tried to optimize it for size:
  - Downscaled from `485x368` to `270x205` (width is fixed by the README)
  - Decreased FPS from 12 to 10
  - Decrease quality from 100 to 70
  
These were the commands I used:
```bash
ffmpeg -i surfaceplot.apng -vf "fps=10,scale=270:-1:flags=lanczos" frames/frame_%04d.png
gifski -o surfaceplot.gif --fps 10 --quality 70 frames/frame_*.png
```

### Before (~22.6MB)
- **`duckplot.gif`** – *4.3 MB*
- **`lineplot.gif`** – *3.2 MB*
- **`markerplot.gif`** – *1.6 MB*
- **`scatterplot.gif`** – *2.8 MB*
- **`sphereplot.gif`** – *5.6 MB*
- **`surfaceplot.gif`** – *5.1 MB*

<p align="center">
<img src="https://github.com/user-attachments/assets/359473d2-73a9-452c-a5f3-cb96e3785dc2" width="270"> <img src="https://github.com/user-attachments/assets/97ec8be4-50f9-428b-b357-25e2479409b8" width="270"> <img src="https://github.com/user-attachments/assets/c212039b-4853-4d26-95a5-5470bf97555e" width="270">
</p>

<p align="center">
<img src="https://github.com/user-attachments/assets/ec7ec42a-3c62-44bf-9275-f735f0304c95" width="270"> <img src="https://github.com/user-attachments/assets/e6bd03fa-6d76-4f3e-8d15-c24a05a5f714" width="270"> <img src="https://github.com/user-attachments/assets/b66ff296-7fbf-4644-9129-37daecca0b62" width="270">
</p>

### After (~5.15MB ~4.4x smaller)
- **`duckplot_low.gif`** – *757 KB*  (**5.7x smaller**)  
- **`lineplot_low.gif`** – *679 KB*  (**4.7x smaller**)  
- **`markerplot_low.gif`** – *575 KB*  (**2.8x smaller**)  
- **`scatterplot_low.gif`** – *639 KB*  (**4.4x smaller**)  
- **`sphereplot_low.gif`** – *1.1 MB*  (**5.1x smaller**)  
- **`surfaceplot_low.gif`** – *1.4 MB*  (**3.6x smaller**)  

<p align="center">
<img src="https://github.com/user-attachments/assets/6d4dacc8-ddf5-445b-a595-80f83befd626" width="270"> <img src="https://github.com/user-attachments/assets/69c6d660-54c9-42aa-bac4-22bb19749e4b" width="270"> <img src="https://github.com/user-attachments/assets/93f5dfda-cf6f-4e24-ae07-11e03be27f7a" width="270">
</p>

<p align="center">
<img src="https://github.com/user-attachments/assets/b7279508-d63e-4546-8cba-c69c7bf16c47" width="270"> <img src="https://github.com/user-attachments/assets/434187eb-3449-472b-b443-03140b7c9a9f" width="270"> <img src="https://github.com/user-attachments/assets/94cab1c6-0980-45c5-a6a1-8781f536a2ef" width="270">
</p>

**Comment by brenocq** [comment]
The GIFs were updated in the `README` in the commit [0fd0651](https://github.com/brenocq/implot3d/commit/0fd065199cd31e286422e4cff6b632485d73ed04)!

Thank you for helping improve ImPlot3D, @gezeta-id! Feel free to check out the [discussions](https://github.com/brenocq/implot3d/discussions/categories/features-and-improvements) if you're interested in contributing to new features 🙂

**Comment by gezeta-id** [comment]
> After (~5.15MB ~4.4x smaller)

That's *great*! Much, much better than my attempt :)

Happy to see it loading so fast in the readme now.
